config/routes.rb
Ebrickandmortar::Application.routes.draw do

  devise_for :store_admins
  resources :stores

  devise_for :admins
  resources :orders

  devise_for :users
  resources :line_items

  resources :carts

  resources :charges 

  get "shop/index"
  resources :pages
root :to => 'pages#welcome' # map / to the custom welcome action of the pages controller

  
resources :stores do
  resources :shoes, :only => [:create, :edit, :index, :new, :show, :destroy, :update]
end

end

app/models/admin.rb
class Admin < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :encryptable, :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
end

app/models/cart.rb
class Cart < ActiveRecord::Base
  has_many :line_items, dependent: :destroy

  def add_shoe(shoe_id)
    current_item = line_items.find_by(shoe_id: shoe_id)
    if current_item
      current_item.quantity += 1
    else
      current_item = line_items.build(shoe_id: shoe_id)
    end
    current_item
  end

  def total_price
    line_items.to_a.sum { |item| item.total_price }
  end

def paypal_url(return_url)
  values = {
    :business => 'eblakescott@gmail.com',
    :cmd => '_cart',
    :upload => 1,
    :return => return_url,
    :invoice => id
  }
  line_items.each_with_index do |item, index|
    values.merge!({
      "amount_#{index+1}" => item.total_price,
      "item_name_#{index+1}" => item.shoe.title,
      "item_number_#{index+1}" => item.id,
      "quantity_#{index+1}" => item.quantity,
      "item_color_#{index+1}" => item.shoe.color,
      "item_size_#{index+1}" => item.shoe.size,
      "item_width_#{index+1}" => item.shoe.width
    })
  end
  "https://www.sandbox.paypal.com/cgi-bin/webscr?" + values.to_query
end



end

app/models/charge.rb
class Charge < ActiveRecord::Base
has_many :line_items, dependent: :destroy

def total_price
    line_items.to_a.sum { |item| item.total_price }
  end
end

app/models/line_item.rb
class LineItem < ActiveRecord::Base
  belongs_to :charge
  belongs_to :shoe
  belongs_to :cart
  attr_accessible :shoe_id, :cart_id, :quantity
  
  def total_price
    shoe.price * quantity
  end
end

app/models/order.rb
class Order < ActiveRecord::Base
attr_accessible :name, :address, :email, :pay_type, :credit_card_number
PAYMENT_TYPES = [ "Visa", "Mastercard", "Discover" ]
  has_many :line_items, dependent: :destroy
  # ...
  validates :name, :address, :email, :credit_card_number, presence: true
  validates :pay_type, inclusion: PAYMENT_TYPES
  def add_line_items_from_cart(cart)
    cart.line_items.each do |item|
      item.cart_id = nil
      line_items << item
    end  
  end
end

app/models/page.rb
class Page < ActiveRecord::Base
attr_accessible :title, :content
end

app/models/shoe.rb
class Shoe < ActiveRecord::Base
  belongs_to :store
  has_many :line_items
  has_many :orders, through: :line_items
  before_destroy :ensure_not_referenced_by_any_line_item
  attr_accessible :title, :description, :image_url, :price, :store_id, :sex, :size, :width, :color  

def self.latest
    Shoe.order(:updated_at).last
  end

def self.search(search)
  if search
    where('title ILIKE ? OR description ILIKE ?', "%#{search}%", "%#{search}%")
  else
    scoped
  end
end

  private

    # ensure that there are no line items referencing this shoe
    def ensure_not_referenced_by_any_line_item
      if line_items.empty?
        return true
      else
        errors.add(:base, 'Line Items present')
        return false
      end
    end

end

app/models/shop.rb
class Shop < ActiveRecord::Base
end

app/models/store.rb
class Store < ActiveRecord::Base
has_many :shoes, dependent: :destroy
belongs_to :store_admin
attr_accessible :title, :description, :image_url, :address

def self.search(search)
  if search
    where('title ILIKE ? OR description ILIKE ? OR address ILIKE ?', "%#{search}%", "%#{search}%", "%#{search}%")
  else
    scoped
  end
end

end

app/models/store_admin.rb
class StoreAdmin < ActiveRecord::Base
has_one :store
  # Include default devise modules. Others available are:
  # :token_authenticatable, :encryptable, :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :encryptable, :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
end

app/controllers/shop_controller.rb
class ShopController < ApplicationController
  def index
  @stores = Store.order(:title)
  end
end

app/controllers/stores_controller.rb
class StoresController < ApplicationController
  before_action :set_store, only: [:show, :edit, :update, :destroy]
  before_filter :store_admin_owns_store?, only: [:edit, :update, :destroy]
  
  # GET /stores
  # GET /stores.json
  def index
    @stores = Store.search(params[:search])
  end

  # GET /stores/1
  # GET /stores/1.json
  def show
    @store = Store.find(params[:id])
    @shoes = @store.shoes
    
    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @store }
    end
  end


  # GET /stores/new
  def new
    @store = Store.new
  end

  # GET /stores/1/edit
  def edit

end

  # POST /stores
  # POST /stores.json
  def create
    @store = Store.new(store_params)

    respond_to do |format|
      if @store.save
        format.html { redirect_to @store, notice: 'Store was successfully created.' }
        format.json { render action: 'show', status: :created, location: @store }
      else
        format.html { render action: 'new' }
        format.json { render json: @store.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /stores/1
  # PATCH/PUT /stores/1.json
  def update
    respond_to do |format|
      if @store.update(store_params)
        format.html { redirect_to @store, notice: 'Store was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @store.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /stores/1
  # DELETE /stores/1.json
  def destroy
    @store.destroy
    respond_to do |format|
      format.html { redirect_to stores_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_store
      @store = Store.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def store_params
      params.require(:store).permit(:title, :description, :address, :image_url)
    end
   
   def store_admin_owns_store?
  @store.store_admin = current_store_admin
end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/charges_helper.rb
module ChargesHelper
end

app/helpers/line_items_helper.rb
module LineItemsHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/shoes_helper.rb
module ShoesHelper
end

app/helpers/shop_helper.rb
module ShopHelper
end

app/helpers/shops_helper.rb
module ShopsHelper
end

app/helpers/stores_helper.rb
module StoresHelper
end

app/views/stores/_form.html.erb
<%= form_for(@store) do |f| %>
  <% if @store.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@store.errors.count, "error") %> prohibited this store from being saved:</h2>

      <ul>
      <% @store.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :address %><br>
    <%= f.text_field :address %>
  </div>
  <div class="field">
    <%= f.label :image_url %><br>
    <%= f.text_field :image_url %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/stores/edit.html.erb
<h1>Editing store</h1>

<%= render 'form' %>

app/views/stores/index.html.erb
<h1>Search Results</h1>

<table class="table">
  <thead>
    <tr>
      <th></th>
      <th></th>
      <th></th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @stores.each do |store| %>
      <tr>
        <td><%= image_tag(store.image_url) %></td>
        <td><strong><%= store.title %></strong></td>
        <td><%= store.description %></td>
        <td><%= store.address %></td>
        <td><%= link_to 'Select', store %></td>
        <% if admin_signed_in? %>
        <td><%= link_to 'Edit', edit_store_path(store) %></td>
        <td><%= link_to 'Destroy', store, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <% end %>
     </tr>
    <% end %>
  </tbody>
</table>

<br>
<% if admin_signed_in? %>
<%= link_to 'New Store', new_store_path %>
<% end %>

app/views/stores/new.html.erb
<h1>New store</h1>

<%= render 'form' %>

<%= link_to 'Back', stores_path %>

app/views/stores/show.html.erb
<div class="row">
<div class="span6">
<p>
  <strong></strong>
  <%= image_tag(@store.image_url) %>
</p>


<p>
  <strong><%= @store.title %></strong>
</p>

<p>
  <strong></strong>
  <%= @store.description %>
</p>

<p>
  <strong>Address:</strong>
  <%= @store.address %>
</p>
</div>
<div class="span6">
<h3>Photo of GLR store and employees</h3>
</div>
</div>
 
<ul class="thumbnails">
  <li class="span3">
   <a href="1/shoes" class="thumbnail">
    <%= image_tag("saucony.png", size: "150x113") %>
    <h3>Shoes</h3>
    <p>Thumbnail caption...</p>
    </a>
  </li>
<li class="span3">
   <a href="1/shoes" class="thumbnail">
    <%= image_tag("saucony.png", size: "150x113") %>
    <h3>Outerwear</h3>
    <p>Thumbnail caption...</p>
    </a>
  </li>
<li class="span3">
   <a href="1/shoes" class="thumbnail">
    <%= image_tag("saucony.png", size: "150x113") %>
    <h3>Baselayers</h3>
    <p>Thumbnail caption...</p>
    </a>
  </li>
<li class="span3">
   <a href="1/shoes" class="thumbnail">
    <%= image_tag("saucony.png", size: "150x113") %>
    <h3>Accessories</h3>
    <p>Thumbnail caption...</p>
    </a>
  </li>
</ul>

<% if store_admin_signed_in? %>
    Signed in as <%= current_store_admin.email %>. 
    <%= link_to "Sign out", destroy_store_admin_session_path, :method => :delete %> | <%=link_to "Edit Store", edit_store_path(@store) %> 
    <% end %>

<br>

<% if admin_signed_in? %>
   <%= link_to 'Delete This Store', [@store], method: :delete, data: { confirm: 'Are you sure?' } %>
  <% end %>
 