config/routes.rb
Ebrickandmortar::Application.routes.draw do

  devise_for :store_admins
  resources :stores

  devise_for :admins
  resources :orders

  devise_for :users
  resources :line_items

  resources :carts

  resources :charges 

  get "shop/index"
  resources :pages
root :to => 'pages#welcome' # map / to the custom welcome action of the pages controller

  
resources :stores do
  resources :shoes, :only => [:create, :edit, :index, :new, :show, :destroy, :update]
end

end

app/models/admin.rb
class Admin < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :encryptable, :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
end

app/models/cart.rb
class Cart < ActiveRecord::Base
  has_many :line_items, dependent: :destroy

  def add_shoe(shoe_id)
    current_item = line_items.find_by(shoe_id: shoe_id)
    if current_item
      current_item.quantity += 1
    else
      current_item = line_items.build(shoe_id: shoe_id)
    end
    current_item
  end

  def total_price
    line_items.to_a.sum { |item| item.total_price }
  end

def paypal_url(return_url)
  values = {
    :business => 'eblakescott@gmail.com',
    :cmd => '_cart',
    :upload => 1,
    :return => return_url,
    :invoice => id
  }
  line_items.each_with_index do |item, index|
    values.merge!({
      "amount_#{index+1}" => item.total_price,
      "item_name_#{index+1}" => item.shoe.title,
      "item_number_#{index+1}" => item.id,
      "quantity_#{index+1}" => item.quantity,
      "item_color_#{index+1}" => item.shoe.color,
      "item_size_#{index+1}" => item.shoe.size,
      "item_width_#{index+1}" => item.shoe.width
    })
  end
  "https://www.sandbox.paypal.com/cgi-bin/webscr?" + values.to_query
end



end

app/models/charge.rb
class Charge < ActiveRecord::Base
has_many :line_items, dependent: :destroy

def total_price
    line_items.to_a.sum { |item| item.total_price }
  end
end

app/models/line_item.rb
class LineItem < ActiveRecord::Base
  belongs_to :charge
  belongs_to :shoe
  belongs_to :cart
  attr_accessible :shoe_id, :cart_id, :quantity
  
  def total_price
    shoe.price * quantity
  end
end

app/models/order.rb
class Order < ActiveRecord::Base
attr_accessible :name, :address, :email, :pay_type, :credit_card_number
PAYMENT_TYPES = [ "Visa", "Mastercard", "Discover" ]
  has_many :line_items, dependent: :destroy
  # ...
  validates :name, :address, :email, :credit_card_number, presence: true
  validates :pay_type, inclusion: PAYMENT_TYPES
  def add_line_items_from_cart(cart)
    cart.line_items.each do |item|
      item.cart_id = nil
      line_items << item
    end  
  end
end

app/models/page.rb
class Page < ActiveRecord::Base
attr_accessible :title, :content
end

app/models/shoe.rb
class Shoe < ActiveRecord::Base
  belongs_to :store
  has_many :line_items
  has_many :orders, through: :line_items
  before_destroy :ensure_not_referenced_by_any_line_item
  attr_accessible :title, :description, :image_url, :price, :store_id, :sex, :size, :width, :color  

def self.latest
    Shoe.order(:updated_at).last
  end

def self.search(search)
  if search
    where('title ILIKE ? OR description ILIKE ?', "%#{search}%", "%#{search}%")
  else
    scoped
  end
end

  private

    # ensure that there are no line items referencing this shoe
    def ensure_not_referenced_by_any_line_item
      if line_items.empty?
        return true
      else
        errors.add(:base, 'Line Items present')
        return false
      end
    end

end

app/models/shop.rb
class Shop < ActiveRecord::Base
end

app/models/store.rb
class Store < ActiveRecord::Base
has_many :shoes, dependent: :destroy
belongs_to :store_admin
attr_accessible :title, :description, :image_url, :address

def self.search(search)
  if search
    where('title ILIKE ? OR description ILIKE ? OR address ILIKE ?', "%#{search}%", "%#{search}%", "%#{search}%")
  else
    scoped
  end
end

end

app/models/store_admin.rb
class StoreAdmin < ActiveRecord::Base
has_one :store
  # Include default devise modules. Others available are:
  # :token_authenticatable, :encryptable, :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :encryptable, :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  before_action :set_cart, only: [:show, :edit, :update, :destroy]
  rescue_from ActiveRecord::RecordNotFound, with: :invalid_cart
  # GET /carts
  # GET /carts.json
  def index
    @carts = Cart.all
  end

  # GET /carts/1
  # GET /carts/1.json
  def show
  end

  # GET /carts/new
  def new
    @cart = Cart.new
  end

  # GET /carts/1/edit
  def edit
  end

  # POST /carts
  # POST /carts.json
  def create
    @cart = Cart.new(cart_params)

    respond_to do |format|
      if @cart.save
        format.html { redirect_to @cart, notice: 'Cart was successfully created.' }
        format.json { render action: 'show', status: :created, location: @cart }
      else
        format.html { render action: 'new' }
        format.json { render json: @cart.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /carts/1
  # PATCH/PUT /carts/1.json
  def update
    respond_to do |format|
      if @cart.update(cart_params)
        format.html { redirect_to @cart, notice: 'Cart was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @cart.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /carts/1
  # DELETE /carts/1.json
  def destroy
    @cart.destroy
      session[:cart_id] = nil 
      respond_to do |format|
      format.html { redirect_to carts_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_cart
      @cart = Cart.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def cart_params
      params[:cart]
    end
    def invalid_cart
      logger.error "Attempt to access invalid cart #{params[:id]}"
      redirect_to root_url, notice: 'Invalid cart'
    end
end

app/controllers/shop_controller.rb
class ShopController < ApplicationController
  def index
  @stores = Store.order(:title)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/charges_helper.rb
module ChargesHelper
end

app/helpers/line_items_helper.rb
module LineItemsHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/shoes_helper.rb
module ShoesHelper
end

app/helpers/shop_helper.rb
module ShopHelper
end

app/helpers/shops_helper.rb
module ShopsHelper
end

app/helpers/stores_helper.rb
module StoresHelper
end

app/views/carts/_form.html.erb
<%= form_for(@cart) do |f| %>
  <% if @cart.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@cart.errors.count, "error") %> prohibited this cart from being saved:</h2>

      <ul>
      <% @cart.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/carts/edit.html.erb
<h1>Editing cart</h1>

<%= render 'form' %>

<%= link_to 'Show', @cart %> |
<%= link_to 'Back', carts_path %>

app/views/carts/index.html.erb
<h1>Listing carts</h1>

<table>
  <thead>
    <tr>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @carts.each do |cart| %>
      <tr>
        <td><%= link_to 'Show', cart %></td>
        <td><%= link_to 'Edit', edit_cart_path(cart) %></td>
        <td><%= link_to 'Destroy', cart, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Cart', new_cart_path %>

app/views/carts/new.html.erb
<h1>New cart</h1>

<%= render 'form' %>

<%= link_to 'Back', carts_path %>

app/views/carts/show.html.erb
<% if notice %>
<p id="notice"><%= notice %></p>
<% end %>

<!-- START_HIGHLIGHT -->
<h2>Your Cart</h2>
<table class="table">
<thead>
    <tr>
      <th></th>
      <th>Quantity</th>
      <th>Name</th>
      <th>Total Price</th>
      <th>Mens or Womens</th>
      <th>Color</th>
      <th>Size</th>
      <th>Width</th>
    </tr>
  </thead>
<!-- END_HIGHLIGHT -->
  <% @cart.line_items.each do |item| %>
    <tr>
      <td><%= image_tag(item.shoe.image_url) %></td>
      <td><%= item.quantity %>&times;</td>
      <td><%= item.shoe.title %></td>
      <td><%= number_to_currency(item.total_price) %></td>
      <td><%= item.shoe.sex %></td>
      <td><%= item.shoe.color %></td>
      <td><%= item.shoe.size %></td>
      <td><%= item.shoe.width %></td>
    </tr>
  <% end %>

  <tr>
    <td>Total</td>
    <td><strong><%= number_to_currency(@cart.total_price) %></strong></td>
<td>
<%= form_tag charges_path do %>
 
  <script src="https://checkout.stripe.com/v2/checkout.js" class="stripe-button"
          data-key="pk_test_xnq5nucYpEcGXsJsm9FaVkfs"
          data-description=""
          data-amount=""></script>
<% end %>
</td>
</tr>
</table>

<%= button_to 'Empty cart', @cart, method: :delete,
    data: { confirm: 'Are you sure?' } %>
<%= link_to "Back", store_path(params[:id]), method: :get %>