config/routes.rb
Ebrickandmortar::Application.routes.draw do

  devise_for :store_admins
  resources :stores

  devise_for :admins
  resources :orders

  devise_for :users
  resources :line_items

  resources :carts

  resources :charges 

  get "shop/index"
  resources :pages
root :to => 'pages#welcome' # map / to the custom welcome action of the pages controller

  
resources :stores do
  resources :shoes, :only => [:create, :edit, :index, :new, :show, :destroy, :update]
end

end

app/models/admin.rb
class Admin < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :encryptable, :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
end

app/models/cart.rb
class Cart < ActiveRecord::Base
  has_many :line_items, dependent: :destroy

  def add_shoe(shoe_id)
    current_item = line_items.find_by(shoe_id: shoe_id)
    if current_item
      current_item.quantity += 1
    else
      current_item = line_items.build(shoe_id: shoe_id)
    end
    current_item
  end

  def total_price
    line_items.to_a.sum { |item| item.total_price }
  end

def paypal_url(return_url)
  values = {
    :business => 'eblakescott@gmail.com',
    :cmd => '_cart',
    :upload => 1,
    :return => return_url,
    :invoice => id
  }
  line_items.each_with_index do |item, index|
    values.merge!({
      "amount_#{index+1}" => item.total_price,
      "item_name_#{index+1}" => item.shoe.title,
      "item_number_#{index+1}" => item.id,
      "quantity_#{index+1}" => item.quantity,
      "item_color_#{index+1}" => item.shoe.color,
      "item_size_#{index+1}" => item.shoe.size,
      "item_width_#{index+1}" => item.shoe.width
    })
  end
  "https://www.sandbox.paypal.com/cgi-bin/webscr?" + values.to_query
end



end

app/models/charge.rb
class Charge < ActiveRecord::Base
has_many :line_items, dependent: :destroy

def total_price
    line_items.to_a.sum { |item| item.total_price }
  end
end

app/models/line_item.rb
class LineItem < ActiveRecord::Base
  belongs_to :charge
  belongs_to :shoe
  belongs_to :cart
  attr_accessible :shoe_id, :cart_id, :quantity
  
  def total_price
    shoe.price * quantity
  end
end

app/models/order.rb
class Order < ActiveRecord::Base
attr_accessible :name, :address, :email, :pay_type, :credit_card_number
PAYMENT_TYPES = [ "Visa", "Mastercard", "Discover" ]
  has_many :line_items, dependent: :destroy
  # ...
  validates :name, :address, :email, :credit_card_number, presence: true
  validates :pay_type, inclusion: PAYMENT_TYPES
  def add_line_items_from_cart(cart)
    cart.line_items.each do |item|
      item.cart_id = nil
      line_items << item
    end  
  end
end

app/models/page.rb
class Page < ActiveRecord::Base
attr_accessible :title, :content
end

app/models/shoe.rb
class Shoe < ActiveRecord::Base
  belongs_to :store
  has_many :line_items
  has_many :orders, through: :line_items
  before_destroy :ensure_not_referenced_by_any_line_item
  attr_accessible :title, :description, :image_url, :price, :store_id, :sex, :size, :width, :color  

def self.latest
    Shoe.order(:updated_at).last
  end

def self.search(search)
  if search
    where('title ILIKE ? OR description ILIKE ?', "%#{search}%", "%#{search}%")
  else
    scoped
  end
end

  private

    # ensure that there are no line items referencing this shoe
    def ensure_not_referenced_by_any_line_item
      if line_items.empty?
        return true
      else
        errors.add(:base, 'Line Items present')
        return false
      end
    end

end

app/models/shop.rb
class Shop < ActiveRecord::Base
end

app/models/store.rb
class Store < ActiveRecord::Base
has_many :shoes, dependent: :destroy
belongs_to :store_admin
attr_accessible :title, :description, :image_url, :address

def self.search(search)
  if search
    where('title ILIKE ? OR description ILIKE ? OR address ILIKE ?', "%#{search}%", "%#{search}%", "%#{search}%")
  else
    scoped
  end
end

end

app/models/store_admin.rb
class StoreAdmin < ActiveRecord::Base
has_one :store
  # Include default devise modules. Others available are:
  # :token_authenticatable, :encryptable, :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :encryptable, :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
end

app/controllers/shoes_controller.rb
class ShoesController < ApplicationController
  before_action :set_shoe, only: [:show, :edit, :update, :destroy]
  before_filter :set_store
  
  # GET /shoes
  # GET /shoes.json
  def index
    @shoes = Shoe.all
    @shoes = @store.shoes.all
    @shoes = @store.shoes.search(params[:search])
  end

  # GET /shoes/1
  # GET /shoes/1.json
  def show
@shoe = @store.shoes.find(params[:id])
  end

  # GET /shoes/new
  def new
    @shoe = @store.shoes.build
  end

  # GET /shoes/1/edit
  def edit
@shoe = @store.shoes.find(params[:id])
  @shoe = @store.shoes.build(params[:shoe])  
end

  # POST /shoes
  # POST /shoes.json
  def create
    @shoe = @store.shoes.build(params[:shoe])

    respond_to do |format|
      if @shoe.save
        format.html { redirect_to [@store, @shoe], notice: 'Shoe was successfully added.' }
        #format.json { render json: @wait, status: :created, location: @wait }
      else
        #format.html { render action: "new" }
        #format.json { render json: @wait.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /shoes/1
  # PATCH/PUT /shoes/1.json
  def update
    @shoe = @store.shoes.find(params[:id])
    respond_to do |format|
      if @shoe.update(shoe_params)
        format.html { redirect_to [@store, @shoe], notice: 'Shoe selections saved. Ready to add your shoes to your shopping cart?' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @shoe.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /shoes/1
  # DELETE /shoes/1.json
  def destroy
    @shoe = @store.shoes.find(params[:id])
    @shoe.destroy
    respond_to do |format|
      format.html { redirect_to shoes_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_shoe
      @shoe = Shoe.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def shoe_params
      params.require(:shoe).permit(:title, :description, :image_url, :price, :sex, :store_id, :size, :width, :color)
    end
def set_store
      @store = Store.find(params[:store_id])
    end
end

app/controllers/shop_controller.rb
class ShopController < ApplicationController
  def index
  @stores = Store.order(:title)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/charges_helper.rb
module ChargesHelper
end

app/helpers/line_items_helper.rb
module LineItemsHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/shoes_helper.rb
module ShoesHelper
end

app/helpers/shop_helper.rb
module ShopHelper
end

app/helpers/shops_helper.rb
module ShopsHelper
end

app/helpers/stores_helper.rb
module StoresHelper
end

app/views/shoes/_form.html.erb
<%= form_for([@store, @shoe]) do |f| %>
  <% if @shoe.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@shoe.errors.count, "error") %> prohibited this shoe from being saved:</h2>

      <ul>
      <% @shoe.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :image_url %><br>
    <%= f.text_field :image_url %>
  </div>
  <div class="field">
    <%= f.label :price %><br>
    <%= f.text_field :price %>
  </div>
    <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/shoes/edit.html.erb
<h1>Editing shoe</h1>

<%= render 'form' %>

<%= link_to 'Show', @shoe %> |
<%= link_to 'Back', shoes_path %>

app/views/shoes/index.html.erb
<h1><%=@store.title%> Shoes</h1>

<table class="table">
  <thead>
    <tr>
      <th></th>
      <th></th>
      <th></th>
      <th></th>
      <th></th>
      <th></th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @store.shoes.each do |shoe| %>
      <tr>
        <td><%= image_tag(shoe.image_url) %></td>
        <td><%= shoe.title %></td>
        <td><%= shoe.description %></td>
        <td>$<%= shoe.price %></td>
        <td><%= link_to 'Select', store_shoe_path(@store, shoe) %></td>
        <% if admin_signed_in? %>
        <td><%= link_to 'Edit', edit_store_shoe_path(@store, shoe) %></td>
        <td><%= link_to 'Destroy', [@store, shoe], method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <% end %> 
     </tr>
    <% end %>
  </tbody>
</table>

<br>
<% if admin_signed_in? %>
<%= link_to 'New Shoe', new_store_shoe_path(@store) %>
<% end %>

app/views/shoes/new.html.erb
<h1>New shoe</h1>

<%= render 'form' %>

app/views/shoes/show.html.erb
<% if notice %>
<div class="alert alert-success"><%= notice %></div>
<% end %>

<%= button_to 'Add to Cart', line_items_path(shoe_id: @shoe)%>

<div class="row">
<div class="span6">

<p>
 <%= @shoe.description %>
</p>

</div>
<div class="span6">
<p>
 <%= image_tag(@shoe.image_url) %>
</p>
<p>
 <strong><%= @shoe.title %></strong>
</p>
<p>
  <strong>Price:</strong>
  $<%= @shoe.price %>
</p>

<p>
  <strong>Store:</strong>
  <%= @store.title %>
</p>
</div>
</div>

<h3>Customize your shoe</h3>
<%= form_for([@store, @shoe]) do |f| %>  
  
<div class="field">
  <%= f.label :sex %><br>
  <%= f.select :sex, [['Mens', 'Mens'], ['Womens', 'Womens']] %>
</div>
<div class="field">
  <%= f.label :color %><br>
  <%= f.select :color, [['Blue', 'Blue'], ['Green', 'Green']] %>
</div> 
<div class="field">
  <%= f.label :size %><br>
  <%= f.select :size, [[1], [1.5], [2]] %>
</div>
  <div class="field">
    <%= f.label :width %><br>
    <%= f.select :width, [['D', 'D'], ['F', 'F']] %>
  </div>
<div class="actions">
    <%= f.submit %>
  </div>
<% end %> 