config/routes.rb
Ebrickandmortar::Application.routes.draw do

  devise_for :store_admins
  resources :stores

  devise_for :admins
  resources :orders

  devise_for :users
  resources :line_items

  resources :carts

  resources :charges 

  get "shop/index"
  resources :pages
root :to => 'pages#welcome' # map / to the custom welcome action of the pages controller

  
resources :stores do
  resources :shoes, :only => [:create, :edit, :index, :new, :show, :destroy, :update]
end

end

app/models/admin.rb
class Admin < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :encryptable, :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
end

app/models/cart.rb
class Cart < ActiveRecord::Base
  has_many :line_items, dependent: :destroy

  def add_shoe(shoe_id)
    current_item = line_items.find_by(shoe_id: shoe_id)
    if current_item
      current_item.quantity += 1
    else
      current_item = line_items.build(shoe_id: shoe_id)
    end
    current_item
  end

  def total_price
    line_items.to_a.sum { |item| item.total_price }
  end

def paypal_url(return_url)
  values = {
    :business => 'eblakescott@gmail.com',
    :cmd => '_cart',
    :upload => 1,
    :return => return_url,
    :invoice => id
  }
  line_items.each_with_index do |item, index|
    values.merge!({
      "amount_#{index+1}" => item.total_price,
      "item_name_#{index+1}" => item.shoe.title,
      "item_number_#{index+1}" => item.id,
      "quantity_#{index+1}" => item.quantity,
      "item_color_#{index+1}" => item.shoe.color,
      "item_size_#{index+1}" => item.shoe.size,
      "item_width_#{index+1}" => item.shoe.width
    })
  end
  "https://www.sandbox.paypal.com/cgi-bin/webscr?" + values.to_query
end



end

app/models/charge.rb
class Charge < ActiveRecord::Base
has_many :line_items, dependent: :destroy

def total_price
    line_items.to_a.sum { |item| item.total_price }
  end
end

app/models/line_item.rb
class LineItem < ActiveRecord::Base
  belongs_to :charge
  belongs_to :shoe
  belongs_to :cart
  attr_accessible :shoe_id, :cart_id, :quantity
  
  def total_price
    shoe.price * quantity
  end
end

app/models/order.rb
class Order < ActiveRecord::Base
attr_accessible :name, :address, :email, :pay_type, :credit_card_number
PAYMENT_TYPES = [ "Visa", "Mastercard", "Discover" ]
  has_many :line_items, dependent: :destroy
  # ...
  validates :name, :address, :email, :credit_card_number, presence: true
  validates :pay_type, inclusion: PAYMENT_TYPES
  def add_line_items_from_cart(cart)
    cart.line_items.each do |item|
      item.cart_id = nil
      line_items << item
    end  
  end
end

app/models/page.rb
class Page < ActiveRecord::Base
attr_accessible :title, :content
end

app/models/shoe.rb
class Shoe < ActiveRecord::Base
  belongs_to :store
  has_many :line_items
  has_many :orders, through: :line_items
  before_destroy :ensure_not_referenced_by_any_line_item
  attr_accessible :title, :description, :image_url, :price, :store_id, :sex, :size, :width, :color  

def self.latest
    Shoe.order(:updated_at).last
  end

def self.search(search)
  if search
    where('title ILIKE ? OR description ILIKE ?', "%#{search}%", "%#{search}%")
  else
    scoped
  end
end

  private

    # ensure that there are no line items referencing this shoe
    def ensure_not_referenced_by_any_line_item
      if line_items.empty?
        return true
      else
        errors.add(:base, 'Line Items present')
        return false
      end
    end

end

app/models/shop.rb
class Shop < ActiveRecord::Base
end

app/models/store.rb
class Store < ActiveRecord::Base
has_many :shoes, dependent: :destroy
belongs_to :store_admin
attr_accessible :title, :description, :image_url, :address

def self.search(search)
  if search
    where('title ILIKE ? OR description ILIKE ? OR address ILIKE ?', "%#{search}%", "%#{search}%", "%#{search}%")
  else
    scoped
  end
end

end

app/models/store_admin.rb
class StoreAdmin < ActiveRecord::Base
has_one :store
  # Include default devise modules. Others available are:
  # :token_authenticatable, :encryptable, :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :encryptable, :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/charges_helper.rb
module ChargesHelper
end

app/helpers/line_items_helper.rb
module LineItemsHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/shoes_helper.rb
module ShoesHelper
end

app/helpers/shop_helper.rb
module ShopHelper
end

app/helpers/shops_helper.rb
module ShopsHelper
end

app/helpers/stores_helper.rb
module StoresHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Ebrickandmortar</title>
  <meta charset="utf-8"> 
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link href="assets/css/bootstrap-responsive.css" rel="stylesheet">
</head>
<body>
<div class="alert alert-success">
<% if admin_signed_in? %>
    Signed in as <%= current_admin.email %>. Not you?
    <%= link_to "Sign out", destroy_admin_session_path, :method => :delete %>
  <% else %>
    <%= link_to "Sign up", new_admin_registration_path %> or <%= link_to "sign in", new_admin_session_path %>
  <% end %>
</div>
</div>
<div class="container">
  <div class="page-header">
<%= link_to(raw("<h1>EBrickandMortar <small>Shop locally on the web</small></h1>"), root_url) %>  
</div>

  <!--<div class="navbar">
    <div class="navbar-inner">
      <ul class="nav">
          <li><%= link_to "Home", root_url %></li> 
          <li class="active"><%= link_to "Shop", shop_index_path %></li>
   
          <li><a href="#">Link</a></li>
          <li><a href="#">Link</a></li>
      
    </ul>
    </div>
  </div>-->


<%= yield %>

</div>
</body>
</html>

app/views/layouts/charges.html.erb
<!DOCTYPE html>
<head>
  <title>Ebrickandmortar</title>
  <meta charset="utf-8"> 
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link href="assets/css/bootstrap-responsive.css" rel="stylesheet">
</head>
<body>
<div class="container">
  <div class="page-header">
<%= link_to(raw("<h1>EBrickandMortar <small>Shop locally on the web</small></h1>"), root_url) %>  
</div>
</div>
  <%= yield %>
</body>
</html>

app/views/pages/_form.html.erb
<%= form_for(@page) do |f| %>
  <% if @page.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@page.errors.count, "error") %> prohibited this page from being saved:</h2>

      <ul>
      <% @page.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :content %><br>
    <%= f.text_area :content %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/pages/edit.html.erb
<h1>Editing page</h1>

<%= render 'form' %>

<%= link_to 'Show', @page %> |
<%= link_to 'Back', pages_path %>

app/views/pages/index.html.erb
<h1>Listing pages</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Content</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @pages.each do |page| %>
      <tr>
        <td><%= page.title %></td>
        <td><%= page.content %></td>
        <td><%= link_to 'Show', page %></td>
        <td><%= link_to 'Edit', edit_page_path(page) %></td>
        <td><%= link_to 'Destroy', page, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Page', new_page_path %>

app/views/pages/new.html.erb
<h1>New page</h1>

<%= render 'form' %>

<%= link_to 'Back', pages_path %>

app/views/pages/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @page.title %>
</p>

<p>
  <strong>Content:</strong>
  <%= @page.content %>
</p>

<%= link_to 'Edit', edit_page_path(@page) %> |
<%= link_to 'Back', pages_path %>

app/views/pages/welcome.html.erb
<!--This view is rendered for the welcome action on the Pages controller-->
<body>
  <div class="hero-unit">
    <!--<h1>Ebrickandmortar</h1>-->
      <h2>Shop your local stores online</h2>
  <fieldset>
<%= form_tag stores_path, class: "form-search", :method => 'get' do %>
  <div>
    <%= label_tag "Search by zip code, store name, or products" %>
    <%= text_field_tag :search, params[:search], placeholder: "e.g., 60616, running shoes" %>
    <%= submit_tag "Search!", :name => nil, class: 'btn btn-large btn-primary' %>
  </div>
  <% end %>
  </fieldset>
</body>